// Code generated by MockGen. DO NOT EDIT.
// Source: ./system.go

// Package mock_config is a generated GoMock package.
package mock_config

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSystemConfig is a mock of SystemConfig interface.
type MockSystemConfig struct {
	ctrl     *gomock.Controller
	recorder *MockSystemConfigMockRecorder
}

// MockSystemConfigMockRecorder is the mock recorder for MockSystemConfig.
type MockSystemConfigMockRecorder struct {
	mock *MockSystemConfig
}

// NewMockSystemConfig creates a new mock instance.
func NewMockSystemConfig(ctrl *gomock.Controller) *MockSystemConfig {
	mock := &MockSystemConfig{ctrl: ctrl}
	mock.recorder = &MockSystemConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemConfig) EXPECT() *MockSystemConfigMockRecorder {
	return m.recorder
}

// DelConfig mocks base method.
func (m *MockSystemConfig) DelConfig(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelConfig", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelConfig indicates an expected call of DelConfig.
func (mr *MockSystemConfigMockRecorder) DelConfig(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelConfig", reflect.TypeOf((*MockSystemConfig)(nil).DelConfig), key)
}

// GetConfig mocks base method.
func (m *MockSystemConfig) GetConfig(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockSystemConfigMockRecorder) GetConfig(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockSystemConfig)(nil).GetConfig), key)
}

// SetConfig mocks base method.
func (m *MockSystemConfig) SetConfig(key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConfig", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConfig indicates an expected call of SetConfig.
func (mr *MockSystemConfigMockRecorder) SetConfig(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfig", reflect.TypeOf((*MockSystemConfig)(nil).SetConfig), key, value)
}
