// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2023-09-11 10:12:43.121281 +0800 CST m=+0.032653126
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cookies": {
            "get": {
                "description": "脚本cookie列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scripts"
                ],
                "summary": "脚本cookie列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                },
                                "data": {
                                    "$ref": "#/definitions/scripts.CookieListResponse"
                                },
                                "msg": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/scripts": {
            "get": {
                "description": "脚本列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scripts"
                ],
                "summary": "脚本列表",
                "parameters": [
                    {
                        "type": "string",
                        "name": "scriptId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                },
                                "data": {
                                    "$ref": "#/definitions/scripts.ListResponse"
                                },
                                "msg": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            },
            "post": {
                "description": "创建脚本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scripts"
                ],
                "summary": "创建脚本",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/scripts.InstallRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                },
                                "data": {
                                    "$ref": "#/definitions/scripts.InstallResponse"
                                },
                                "msg": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/scripts/{scriptId}": {
            "get": {
                "description": "获取脚本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scripts"
                ],
                "summary": "获取脚本",
                "parameters": [
                    {
                        "type": "string",
                        "name": "scriptId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                },
                                "data": {
                                    "$ref": "#/definitions/scripts.GetResponse"
                                },
                                "msg": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            },
            "put": {
                "description": "更新脚本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scripts"
                ],
                "summary": "更新脚本",
                "parameters": [
                    {
                        "type": "string",
                        "name": "scriptId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/scripts.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                },
                                "data": {
                                    "$ref": "#/definitions/scripts.UpdateResponse"
                                },
                                "msg": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除脚本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scripts"
                ],
                "summary": "删除脚本",
                "parameters": [
                    {
                        "type": "string",
                        "name": "scriptId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/scripts.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                },
                                "data": {
                                    "$ref": "#/definitions/scripts.DeleteResponse"
                                },
                                "msg": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/values": {
            "get": {
                "description": "值储存空间列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scripts"
                ],
                "summary": "值储存空间列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                },
                                "data": {
                                    "$ref": "#/definitions/scripts.StorageListResponse"
                                },
                                "msg": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/values/{storageName}": {
            "get": {
                "description": "脚本值列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scripts"
                ],
                "summary": "脚本值列表",
                "parameters": [
                    {
                        "type": "string",
                        "name": "storageName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                },
                                "data": {
                                    "$ref": "#/definitions/scripts.ValueListResponse"
                                },
                                "msg": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "BadRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码",
                    "type": "integer",
                    "format": "int32"
                },
                "msg": {
                    "description": "错误信息",
                    "type": "string"
                }
            }
        },
        "cookie.Cookie": {
            "type": "object"
        },
        "script_entity.Metadata": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "script_entity.ScriptState": {
            "description": "ScriptState enum type:\n- ScriptStateEnable: enable\n- ScriptStateDisable: disable\n- RuntimeScriptCat: scriptcat",
            "type": "string",
            "enum": [
                "enable",
                "disable",
                "scriptcat"
            ]
        },
        "script_entity.Status": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "scripts.Cookie": {
            "type": "object",
            "properties": {
                "cookie_space": {
                    "type": "string"
                },
                "cookies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cookie.Cookie"
                    }
                },
                "created_at": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "scripts.CookieListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scripts.Cookie"
                    }
                }
            }
        },
        "scripts.DeleteRequest": {
            "type": "object",
            "properties": {
                "scriptId": {
                    "type": "string"
                }
            }
        },
        "scripts.DeleteResponse": {
            "type": "object"
        },
        "scripts.GetResponse": {
            "type": "object",
            "properties": {
                "script": {
                    "$ref": "#/definitions/scripts.Script"
                }
            }
        },
        "scripts.InstallRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "scripts.InstallResponse": {
            "type": "object",
            "properties": {
                "scripts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scripts.Script"
                    }
                }
            }
        },
        "scripts.ListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scripts.Script"
                    }
                }
            }
        },
        "scripts.Script": {
            "type": "object",
            "properties": {
                "code,omitempty": {
                    "type": "string"
                },
                "created_time": {
                    "$ref": "#/definitions/time.Time"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/script_entity.Metadata"
                },
                "name": {
                    "type": "string"
                },
                "self_metadata": {
                    "$ref": "#/definitions/script_entity.Metadata"
                },
                "state": {
                    "$ref": "#/definitions/script_entity.ScriptState"
                },
                "status": {
                    "$ref": "#/definitions/script_entity.Status"
                },
                "updated_time": {
                    "$ref": "#/definitions/time.Time"
                }
            }
        },
        "scripts.Storage": {
            "type": "object",
            "properties": {
                "link_script_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "scripts.StorageListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scripts.Storage"
                    }
                }
            }
        },
        "scripts.UpdateRequest": {
            "type": "object",
            "properties": {
                "script": {
                    "$ref": "#/definitions/scripts.Script"
                },
                "scriptId": {
                    "type": "string"
                }
            }
        },
        "scripts.UpdateResponse": {
            "type": "object"
        },
        "scripts.Value": {
            "type": "object",
            "properties": {
                "created_time": {
                    "$ref": "#/definitions/time.Time"
                },
                "key": {
                    "type": "string"
                },
                "storage_name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "scripts.ValueListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scripts.Value"
                    }
                }
            }
        },
        "time.Time": {
            "type": "string"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "云猫 API 文档",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
