basePath: /api/v1
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
  cookie.Cookie:
    type: object
  script_entity.Metadata:
    additionalProperties:
      items:
        type: string
      type: array
    type: object
  script_entity.ScriptState:
    description: |-
      ScriptState enum type:
      - ScriptStateEnable: enable
      - ScriptStateDisable: disable
      - RuntimeScriptCat: scriptcat
    enum:
    - enable
    - disable
    - scriptcat
    type: string
  script_entity.Status:
    additionalProperties:
      type: string
    type: object
  scripts.Cookie:
    properties:
      cookie_space:
        type: string
      cookies:
        items:
          $ref: '#/definitions/cookie.Cookie'
        type: array
      created_at:
        type: integer
      url:
        type: string
    type: object
  scripts.CookieListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/scripts.Cookie'
        type: array
    type: object
  scripts.DeleteRequest:
    properties:
      scriptId:
        type: string
    type: object
  scripts.DeleteResponse:
    type: object
  scripts.GetResponse:
    properties:
      script:
        $ref: '#/definitions/scripts.Script'
    type: object
  scripts.InstallRequest:
    properties:
      code:
        type: string
    type: object
  scripts.InstallResponse:
    properties:
      scripts:
        items:
          $ref: '#/definitions/scripts.Script'
        type: array
    type: object
  scripts.ListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/scripts.Script'
        type: array
    type: object
  scripts.Script:
    properties:
      code,omitempty:
        type: string
      created_time:
        $ref: '#/definitions/time.Time'
      id:
        type: string
      metadata:
        $ref: '#/definitions/script_entity.Metadata'
      name:
        type: string
      self_metadata:
        $ref: '#/definitions/script_entity.Metadata'
      state:
        $ref: '#/definitions/script_entity.ScriptState'
      status:
        $ref: '#/definitions/script_entity.Status'
      updated_time:
        $ref: '#/definitions/time.Time'
    type: object
  scripts.Storage:
    properties:
      link_script_id:
        items:
          type: string
        type: array
      name:
        type: string
    type: object
  scripts.StorageListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/scripts.Storage'
        type: array
    type: object
  scripts.UpdateRequest:
    properties:
      script:
        $ref: '#/definitions/scripts.Script'
      scriptId:
        type: string
    type: object
  scripts.UpdateResponse:
    type: object
  scripts.Value:
    properties:
      created_time:
        $ref: '#/definitions/time.Time'
      key:
        type: string
      storage_name:
        type: string
      value:
        type: string
    type: object
  scripts.ValueListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/scripts.Value'
        type: array
    type: object
  time.Time:
    type: string
info:
  title: 云猫 API 文档
  version: 1.0.0
paths:
  /cookies:
    get:
      consumes:
      - application/json
      description: 脚本cookie列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.CookieListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 脚本cookie列表
      tags:
      - scripts
  /scripts:
    get:
      consumes:
      - application/json
      description: 脚本列表
      parameters:
      - in: query
        name: scriptId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.ListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 脚本列表
      tags:
      - scripts
    post:
      consumes:
      - application/json
      description: 创建脚本
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.InstallRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.InstallResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 创建脚本
      tags:
      - scripts
  /scripts/{scriptId}:
    delete:
      consumes:
      - application/json
      description: 删除脚本
      parameters:
      - in: path
        name: scriptId
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.DeleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.DeleteResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 删除脚本
      tags:
      - scripts
    get:
      consumes:
      - application/json
      description: 获取脚本
      parameters:
      - in: path
        name: scriptId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.GetResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取脚本
      tags:
      - scripts
    put:
      consumes:
      - application/json
      description: 更新脚本
      parameters:
      - in: path
        name: scriptId
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.UpdateResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 更新脚本
      tags:
      - scripts
  /values:
    get:
      consumes:
      - application/json
      description: 值储存空间列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.StorageListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 值储存空间列表
      tags:
      - scripts
  /values/{storageName}:
    get:
      consumes:
      - application/json
      description: 脚本值列表
      parameters:
      - in: path
        name: storageName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.ValueListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 脚本值列表
      tags:
      - scripts
swagger: "2.0"
