basePath: /api/v1
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
  auth.Token:
    properties:
      createtime:
        type: integer
      data_encryption_key:
        type: string
      id:
        type: string
      token:
        type: string
      updatetime:
        type: integer
    type: object
  auth.TokenCreateRequest:
    properties:
      token_id:
        type: string
    type: object
  auth.TokenCreateResponse:
    properties:
      token:
        $ref: '#/definitions/auth.Token'
    type: object
  auth.TokenDeleteRequest:
    properties:
      tokenId:
        type: string
    type: object
  auth.TokenDeleteResponse:
    type: object
  auth.TokenListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/auth.Token'
        type: array
    type: object
  cookie_entity.HttpCookie:
    properties:
      domain:
        description: optional
        type: string
      expirationDate,omitempty:
        description: optional 到期时间戳
        type: integer
      expires:
        $ref: '#/definitions/time.Time'
        description: optional
      http_only:
        type: boolean
      max_age:
        description: |-
          =0 means no 'Max-Age' attribute specified.
          MaxAge<0 means delete cookie now, equivalently 'Max-Age: 0'
          MaxAge>0 means Max-Age attribute present and given in seconds
        type: integer
      name:
        type: string
      path:
        description: optional
        type: string
      same_site:
        type: string
      secure:
        type: boolean
      value:
        type: string
    type: object
  script_entity.Metadata:
    additionalProperties:
      items:
        type: string
      type: array
    type: object
  script_entity.ScriptState:
    description: |-
      ScriptState enum type:
      - ScriptStateEnable: enable
      - ScriptStateDisable: disable
      - RuntimeScriptCat: scriptcat
    enum:
    - enable
    - disable
    - scriptcat
    type: string
  script_entity.Status:
    additionalProperties:
      type: string
    type: object
  scripts.Cookie:
    properties:
      cookies:
        items:
          $ref: '#/definitions/cookie_entity.HttpCookie'
        type: array
      createtime:
        type: integer
      host:
        type: string
      storage_name:
        type: string
    type: object
  scripts.CookieListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/scripts.Cookie'
        type: array
    type: object
  scripts.DeleteCookieRequest:
    properties:
      host:
        type: string
      storageName:
        type: string
    type: object
  scripts.DeleteCookieResponse:
    type: object
  scripts.DeleteRequest:
    properties:
      scriptId:
        type: string
    type: object
  scripts.DeleteResponse:
    type: object
  scripts.DeleteValueRequest:
    properties:
      key:
        type: string
      storageName:
        type: string
    type: object
  scripts.DeleteValueResponse:
    type: object
  scripts.GetResponse:
    properties:
      script:
        $ref: '#/definitions/scripts.Script'
    type: object
  scripts.InstallRequest:
    properties:
      code:
        type: string
    type: object
  scripts.InstallResponse:
    properties:
      scripts:
        items:
          $ref: '#/definitions/scripts.Script'
        type: array
    type: object
  scripts.ListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/scripts.Script'
        type: array
    type: object
  scripts.RunRequest:
    properties:
      scriptId:
        type: string
    type: object
  scripts.RunResponse:
    type: object
  scripts.Script:
    properties:
      code,omitempty:
        type: string
      createtime:
        type: integer
      id:
        type: string
      metadata:
        $ref: '#/definitions/script_entity.Metadata'
      name:
        type: string
      self_metadata:
        $ref: '#/definitions/script_entity.Metadata'
      state:
        $ref: '#/definitions/script_entity.ScriptState'
      status:
        $ref: '#/definitions/script_entity.Status'
      updatetime:
        type: integer
    type: object
  scripts.SetCookieRequest:
    properties:
      cookies:
        items:
          $ref: '#/definitions/cookie_entity.HttpCookie'
        type: array
      storageName:
        type: string
    type: object
  scripts.SetCookieResponse:
    type: object
  scripts.SetValueRequest:
    properties:
      storageName:
        type: string
      values:
        items:
          $ref: '#/definitions/scripts.Value'
        type: array
    type: object
  scripts.SetValueResponse:
    type: object
  scripts.StopRequest:
    properties:
      scriptId:
        type: string
    type: object
  scripts.StopResponse:
    type: object
  scripts.Storage:
    properties:
      link_script_id:
        items:
          type: string
        type: array
      name:
        type: string
    type: object
  scripts.StorageListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/scripts.Storage'
        type: array
    type: object
  scripts.UpdateRequest:
    properties:
      script:
        $ref: '#/definitions/scripts.Script'
      scriptId:
        type: string
    type: object
  scripts.UpdateResponse:
    type: object
  scripts.Value:
    properties:
      createtime:
        type: integer
      key:
        type: string
      storage_name:
        type: string
      value:
        $ref: '#/definitions/value_entity.ValueString'
    type: object
  scripts.ValueListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/scripts.Value'
        type: array
    type: object
  scripts.WatchResponse:
    type: object
  time.Time:
    type: string
  value_entity.ValueString:
    type: object
info:
  title: 云猫 API 文档
  version: 1.0.0
paths:
  /cookies/{storageName}:
    delete:
      consumes:
      - application/json
      description: 删除cookie
      parameters:
      - in: path
        name: storageName
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.DeleteCookieRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.DeleteCookieResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 删除cookie
      tags:
      - scripts
    get:
      consumes:
      - application/json
      description: 脚本cookie列表
      parameters:
      - in: path
        name: storageName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.CookieListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 脚本cookie列表
      tags:
      - scripts
    post:
      consumes:
      - application/json
      description: 设置cookie
      parameters:
      - in: path
        name: storageName
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.SetCookieRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.SetCookieResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 设置cookie
      tags:
      - scripts
  /scripts:
    get:
      consumes:
      - application/json
      description: 脚本列表
      parameters:
      - in: query
        name: scriptId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.ListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 脚本列表
      tags:
      - scripts
    post:
      consumes:
      - application/json
      description: 创建脚本
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.InstallRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.InstallResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 创建脚本
      tags:
      - scripts
  /scripts/{scriptId}:
    delete:
      consumes:
      - application/json
      description: 删除脚本
      parameters:
      - in: path
        name: scriptId
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.DeleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.DeleteResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 删除脚本
      tags:
      - scripts
    get:
      consumes:
      - application/json
      description: 获取脚本
      parameters:
      - in: path
        name: scriptId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.GetResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取脚本
      tags:
      - scripts
    put:
      consumes:
      - application/json
      description: 更新脚本
      parameters:
      - in: path
        name: scriptId
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.UpdateResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 更新脚本
      tags:
      - scripts
  /scripts/{scriptId}/run:
    post:
      consumes:
      - application/json
      description: 运行脚本
      parameters:
      - in: path
        name: scriptId
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.RunRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.RunResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 运行脚本
      tags:
      - scripts
  /scripts/{scriptId}/stop:
    post:
      consumes:
      - application/json
      description: 停止脚本
      parameters:
      - in: path
        name: scriptId
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.StopRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.StopResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 停止脚本
      tags:
      - scripts
  /scripts/{scriptId}/watch:
    get:
      consumes:
      - application/json
      description: 监听脚本
      parameters:
      - in: path
        name: scriptId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.WatchResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 监听脚本
      tags:
      - scripts
  /storages:
    get:
      consumes:
      - application/json
      description: 值储存空间列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.StorageListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 值储存空间列表
      tags:
      - scripts
  /tokens:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: token_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/auth.TokenListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      tags:
      - auth
    post:
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/auth.TokenCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/auth.TokenCreateResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      tags:
      - auth
  /tokens/{tokenId}:
    delete:
      consumes:
      - application/json
      parameters:
      - in: path
        name: tokenId
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/auth.TokenDeleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/auth.TokenDeleteResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      tags:
      - auth
  /values/{storageName}:
    get:
      consumes:
      - application/json
      description: 脚本值列表
      parameters:
      - in: path
        name: storageName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.ValueListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 脚本值列表
      tags:
      - scripts
    post:
      consumes:
      - application/json
      description: 设置脚本值
      parameters:
      - in: path
        name: storageName
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.SetValueRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.SetValueResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 设置脚本值
      tags:
      - scripts
  /values/{storageName}/{key}:
    delete:
      consumes:
      - application/json
      description: 删除脚本值
      parameters:
      - in: path
        name: storageName
        required: true
        type: string
      - in: path
        name: key
        required: true
        type: string
      - in: body
        name: body
        schema:
          $ref: '#/definitions/scripts.DeleteValueRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/scripts.DeleteValueResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 删除脚本值
      tags:
      - scripts
swagger: "2.0"
